export const dummyData = [
  {
    school_name: "Sekolah Dasar Negeri 01 Jakarta",
    school_npsn: "1234567890",
    school_category: "Negeri",
    school_type: "SD",
    school_address: "Jl. Merdeka No.1, Jakarta",
    school_province: "DKI Jakarta",
    school_city: "Jakarta Pusat",
    school_district: "Gambir",
    school_subdistrict: "Merdeka",
    school_telp: "+6221-12345678",
    school_email: "sd01@jakarta.sch.id",

    students: {
      student_total: 500,
      total_a1_egg: 200,
      total_a1_cow_milk: 150,
      total_a1_seafood: 100,
      total_a1_red_meat: 80,
      total_a2_fruit: 500,
      total_a2_vegetable: 400,
      total_a2_latex_fruit: 50,
      total_a3_sesame: 30,
      total_a3_herbs_spices: 40,
      total_a4_food_color: 10,
      total_a4_food_preservative: 20,
      total_a4_artificial_flavors: 5,
      total_a5_chocolate: 15,
      total_a5_breads_cakes: 100,
      total_a5_food_instant: 50,
      total_vegan: 60,
    },
    imt_data: {
      total_imt_kurus_ringan: 30,
      total_imt_kurus_berat: 20,
      total_imt_normal: 400,
      total_imt_gemuk_ringan: 40,
      total_imt_gemuk_berat: 10,
      total_imt_normal_pct: 0.8,
      coordinate: {
        lat: -6.2088,
        lng: 106.8456,
      },

      imt_stats: [
        {
          month: "2023-01",
          total_imt_kurus_ringan: 30,
          total_imt_kurus_berat: 20,
          total_imt_normal: 400,
          total_imt_gemuk_ringan: 40,
          total_imt_gemuk_berat: 10,
        },
        {
          month: "2023-02",
          total_imt_kurus_ringan: 35,
          total_imt_kurus_berat: 15,
          total_imt_normal: 420,
          total_imt_gemuk_ringan: 50,
          total_imt_gemuk_berat: 5,
        },
      ],
    },
  },
  {
    school_name: "SMA Negeri 2 Surabaya",
    school_npsn: "0987654321",
    school_category: "Negeri",
    school_type: "SMA",
    school_address: "Jl. Raya No.2, Surabaya",
    school_province: "Jawa Timur",
    school_city: "Surabaya",
    school_district: "Gubeng",
    school_subdistrict: "Ketintang",
    school_telp: "+6231-98765432",
    school_email: "sma2@surabaya.sch.id",

    students: {
      student_total: 600,
      total_a1_egg: 250,
      total_a1_cow_milk: 200,
      total_a1_seafood: 150,
      total_a1_red_meat: 100,
      total_a2_fruit: 550,
      total_a2_vegetable: 450,
      total_a2_latex_fruit: 60,
      total_a3_sesame: 25,
      total_a3_herbs_spices: 30,
      total_a4_food_color: 15,
      total_a4_food_preservative: 25,
      total_a4_artificial_flavors: 10,
      total_a5_chocolate: 20,
      total_a5_breads_cakes: 120,
      total_a5_food_instant: 60,
      total_vegan: 70,
    },
    imt_data: {
      total_imt_kurus_ringan: 40,
      total_imt_kurus_berat: 25,
      total_imt_normal: 500,
      total_imt_gemuk_ringan: 45,
      total_imt_gemuk_berat: 15,
      total_imt_normal_pct: 0.5,
      coordinate: {
        lat: -7.2504,
        lng: 112.7688,
      },

      imt_stats: [
        {
          month: "2023-01",
          total_imt_kurus_ringan: 40,
          total_imt_kurus_berat: 25,
          total_imt_normal: 500,
          total_imt_gemuk_ringan: 45,
          total_imt_gemuk_berat: 15,
        },
        {
          month: "2023-02",
          total_imt_kurus_ringan: 45,
          total_imt_kurus_berat: 20,
          total_imt_normal: 510,
          total_imt_gemuk_ringan: 55,
          total_imt_gemuk_berat: 10,
        },
      ],
    },
  },
];

export const data_imt = {
  student_total: 1100,
  imt_stats: [
    {
      month: "Jan",
      total_imt_kurus_ringan: 66,
      total_imt_kurus_berat: 44,
      total_imt_normal: 880,
      total_imt_gemuk_ringan: 88,
      total_imt_gemuk_berat: 22,
    },
    {
      month: "Feb",
      total_imt_kurus_ringan: 77,
      total_imt_kurus_berat: 33,
      total_imt_normal: 869,
      total_imt_gemuk_ringan: 99,
      total_imt_gemuk_berat: 22,
    },
    {
      month: "Mar",
      total_imt_kurus_ringan: 62,
      total_imt_kurus_berat: 40,
      total_imt_normal: 891,
      total_imt_gemuk_ringan: 92,
      total_imt_gemuk_berat: 15,
    },
    {
      month: "Apr",
      total_imt_kurus_ringan: 70,
      total_imt_kurus_berat: 48,
      total_imt_normal: 858,
      total_imt_gemuk_ringan: 99,
      total_imt_gemuk_berat: 25,
    },
    {
      month: "May",
      total_imt_kurus_ringan: 55,
      total_imt_kurus_berat: 42,
      total_imt_normal: 876,
      total_imt_gemuk_ringan: 106,
      total_imt_gemuk_berat: 21,
    },
    {
      month: "Jun",
      total_imt_kurus_ringan: 59,
      total_imt_kurus_berat: 31,
      total_imt_normal: 884,
      total_imt_gemuk_ringan: 104,
      total_imt_gemuk_berat: 22,
    },
    {
      month: "Jul",
      total_imt_kurus_ringan: 73,
      total_imt_kurus_berat: 37,
      total_imt_normal: 869,
      total_imt_gemuk_ringan: 99,
      total_imt_gemuk_berat: 22,
    },
    {
      month: "Aug",
      total_imt_kurus_ringan: 68,
      total_imt_kurus_berat: 46,
      total_imt_normal: 862,
      total_imt_gemuk_ringan: 104,
      total_imt_gemuk_berat: 20,
    },
    {
      month: "Sep",
      total_imt_kurus_ringan: 64,
      total_imt_kurus_berat: 35,
      total_imt_normal: 891,
      total_imt_gemuk_ringan: 95,
      total_imt_gemuk_berat: 15,
    },
    {
      month: "Oct",
      total_imt_kurus_ringan: 75,
      total_imt_kurus_berat: 44,
      total_imt_normal: 854,
      total_imt_gemuk_ringan: 108,
      total_imt_gemuk_berat: 19,
    },
    {
      month: "Nov",
      total_imt_kurus_ringan: 57,
      total_imt_kurus_berat: 40,
      total_imt_normal: 884,
      total_imt_gemuk_ringan: 101,
      total_imt_gemuk_berat: 18,
    },
    {
      month: "Dec",
      total_imt_kurus_ringan: 66,
      total_imt_kurus_berat: 33,
      total_imt_normal: 873,
      total_imt_gemuk_ringan: 106,
      total_imt_gemuk_berat: 22,
    },
  ],
};
